version: '3'
services:
  bridge:
    image: eclipse/zenoh-bridge-ros2dds:latest
    environment:
      - ROS_DISTRO=humble
      - VISUALIZE_IP=$VISUALIZE_IP
    network_mode: "host"
    #ports:
    #  - "7447:7447"
    volumes:
      - ./config:/config
    command:
      - -e tcp/$VISUALIZE_IP:7447 -c /config/zenoh-bridge-ros2dds.json5

  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe-devel-20250131-amd64
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: "host"
    command: ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit rviz:=false
