FROM ghcr.io/autowarefoundation/autoware-universe:humble-20230715-prebuilt-cuda-amd64

# Avoid blank rviz2 issue: https://github.com/ros2/rviz/issues/834#issuecomment-1509095937
RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository -y ppa:kisak/kisak-mesa
RUN apt-get update
RUN apt-get -y install --only-upgrade *mesa*

# Download necessary packages
RUN apt-get update 
RUN apt-get install -y wget unzip tmux inetutils-ping parallel
RUN python3 -m pip install gdown

# Env
WORKDIR /root/
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# Install Rust
RUN apt-get install -y build-essential curl llvm-dev libclang-dev cmake
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Build zenoh-bridge-ros2dds
RUN git clone https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds.git
RUN cd zenoh-plugin-ros2dds && cargo build --release -p zenoh-bridge-ros2dds

# Install Autoware map
RUN gdown -O ~/autoware_map/ 'https://docs.google.com/uc?export=download&id=1499_nsbUbIeturZaDj7jhUownh5fvXHd'
RUN unzip -d ~/autoware_map ~/autoware_map/sample-map-planning.zip

# Set home folder
WORKDIR runtime

CMD bash
