FROM ubuntu:22.04
RUN apt-get update 
# Install necessary packages
RUN apt-get install -y git wget unzip tmux inetutils-ping

# Install Rust
RUN apt-get install -y build-essential curl llvm-dev libclang-dev cmake
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Build autoware_manual_control_rs
RUN git clone https://github.com/evshary/autoware_manual_control_rs.git -b main
RUN cd autoware_manual_control_rs && cargo build --release

WORKDIR autoware_manual_control_rs

CMD bash
